

export const categoryToSubcatIds = new Map([
  ["Signs, Symptoms and Presentations", ["recK065jpAdzeqtXN", "rect0JVhkFjJ3bnwy", "recr1Fup2jyqdbupB"]],
  ["Abdominal and Gastrointestinal Disorders", ["recJdsL9BMhWlnmFj", "recaMVmSLBjZClZ8V", "recg973IkpUQyBgdk", "rechgN8lxnGfrB8YK", "reco2hohS8aaylq2s", "rec341CAEeWi3DiIp", "rec7ItIa2nizt2Lh1", "recwd5mGO6tLoEo8V", "reccsRdpMFPJuJyAY", "recs9rSzz3o8EBFO4", "rec1aKvigo17k14Eq", "recfZruB0Q0aKUP14"]],
  ["Cardiovascular Disorders", ["recglOC1p7xyNNH3y", "recPlaKdsJXoxVhES", "recxWIwYBSNOPI9d1", "rec6BhlaiZtcprdLq", "recX9XqMLzyNTixND", "rec3CVZb9tf10EZiJ", "recjUKyeGosQgfG6o", "recaBCvjTBCy0plfl", "rec9BQidrLQUR57nS", "recPiEHNaZstKOV0r", "recd44WiR7l0wukbW", "recs0wa5zFNGI0ydD", "recSq2XIAnT6NxIqN", "recL8oXUExUc3VN5L"]],
  ["Cutaneous Disorders", ["recZ2YjN9ZVHohlSQ", "rec0FNwCpw2XXUhhh", "rec9bJXGp7CszROax", "recIZMJMt7WgltTal", "recmj3rxPYxrIbqdp", "recXsQKuVMFUQ3VEi", "recn4szGxwB8oiJWh"]],
  ["Endocrine Metabolic and Nutritional Disorders", ["recxH0upWZ4bZWOFq", "recPCN4LoFYOaSlHu", "recSq2XIAnT6NxIqN", "rec237hgtSJGOMNgf", "rechx9fuCcyuwhKqt", "recC4oXaYFlsc9s4Q", "recPPc0zjj3bCLdUB", "rec3sjGSFAjoGg6B4", "recyD6USONqJrWpA9"]],
  ["Environmental Disorders", ["recceX6Jl9NiiklDr", "recaJKw0GmnRlrdI4", "recpNb536JE5wmrqQ", "recHVFjCyEAMrV93r", "recafha6TQdKgXLeL", "recvJ6oNl7jYmdcPp", "recoG2XwYHTETJoXy"]],
  ["HEENT Disorders", ["recrf8wLK77Izk0kP", "reciOYqx0IvFrJQTu", "recvDudvWQ7w6opAL", "recKjze3JpZAZITvv", "reczFaMav53fnupv3"]],
  ["Hematologic Disorders", ["recgumnA7uX0qSBub", "rec3y0Cs09CnuwwZW", "recN6SjYY8oXR8hks", "rec4pa7OP40DcjpMS", "recOfMFQYud4EVuB0", "rectRDjFmQyaq7VBY", "recy2Ld0ruoPey4Wb"]],
  ["Immune System Disorders", ["recLo64cZ2bqaioF4", "recyDlkkqtC1iSfpm", "rec76RTdWeybZXMZ6", "recc1Uroa6gqV8Z0F", "rec3z9Oas1acbRoTa", "recDQNtd083Q7T20f"]],
  ["Systemic Infectious Disorders", ["recdP5ezk8JhRcWgh", "recGtsiGMkEcITWAT", "recKsHp4wINiGn1U9", "reci7SAedjmVsR6NZ", "recnu0rZfX3kHr7Ci", "recl9aog6ghHPdFhb", "recN9R3Wg2xYxiBmc", "rec8204KedeGtEjLg"]],
  ["Musculoskeletal Disorders (Nontraumatic)", ["rec58vK6jK35cC7KL", "recLpL3uRIqRdcwjO", "recAU9gIycCuykaQ7", "recXSVPcE2UTdQ754", "recH6iAEcor3wE44X", "recwi3eXXTxQINhUw"]],
  ["Nervous System Disorders", ["recbsmsbSGSCs7pTd", "receh67BOoIXNsboC", "rec2pxcKFWVZ8TJ9i", "recFzXJWzYIiOfdsV", "recWllgwwNeQawtws", "rec5N0MuCgQPVmAxw", "recn3JB7mF5jxMwZ5", "rec14BkxDX3unLfnk", "recR2UZK5fcq5Eib3", "recyszhwrHPU6uFFq", "recTudqZywHkUEHlh", "recaJGPEFVcHJpb4F", "recwB6bpmHU75cfdP", "recL1VhuB5fFhtNhZ"]],
  ["Obstetrics and Gynecology", ["rechPXDlzx67qpCoD", "recmFZ0LAH71eevpo", "recRiEjq8LHfwNveO", "recWAjlcGjeli6AqU", "recZz2LzqHYvtXXPB", "rec5H9ZYkercbhCN1", "recc5CCodkkJF41iT", "recrYtWkA2Thmzefb", "rec9ttUkW77bFKL6i"]],
  ["Psychobehavioral Disorders", ["recdJqmAo6534cydc", "recWBANLvhSGQr0sg", "recksSMDwSauBiO7R", "recqlDwpw9a9bXYVK", "rec4DBjI1AEoQjv2d", "rec03V8FcuxkttRYj", "recGlQKFDlSECQ9lY", "reczSKXrXg8jeFUdj"]],
  ["Renal and Urogenital Disorders", ["recjZ7Ph0ONQmNMSm", "recAFXExPijhWGe0Y", "recSzpAw2UPxgpaUL", "recU4OHHhTjtpQz5a", "recuETJrWf16YxRs5", "recmiZVxrrSCBQqi5", "reccRLnAThF2csQEF", "rechOMPSd5QXpV5su", "recvZqXSYh788HjcI"]],
  ["Thoracic Respiratory Disorders", ["recJMGTuhry7QPgj3", "rec69uGKTlheOYBJj", "rec3Z9F2pGhkN85gD", "recRex7KAFAyBQF9c", "recEbDuBNNPPq6t4f", "rec3bYe45fmlphxvr", "receiNyLbrrv8uyXB", "rech28j02eeFYQjvA", "recq8zFcZqPGsdUnt"]],
  ["Toxicologic Disorders", ["reczaBYFWSfdlhy96", "recNXPMmeAFpNhz7b", "recGE77ZAWvCuM7zw", "recOUSndwlaEq9riN", "recMyaspBGgXoIqmG", "reclw2QQSTOEZPQ9L", "recKAgx1cxL7kefAf", "recLoFNVXYSG5C8oP", "recPQu8AZy6FhzuEX", "reccMnB7rx69FK0Tj", "recTlSlT9LPMfqcHd", "recC5Ay9SMLbsgojV", "reclvRnhUnm8pjn2L", "recC3M5tBSIJlYILV", "recQnoDBn5Yr3T6fz", "recGtT8jLHAkyvbeH", "recIBCq90KVqT4sb2", "recQTLbSPQq9CdJSv", "rec2hCbNWHfYLNMe1", "recouDJgXjnqJQu3l", "recFVZq1ceunskqOc", "recriNs80mkkQVXZq", "rec6hbI3e15WrxyB0", "recCU8B4Ax2awTCRh", "recnjRJKZ6Zj4aMrR", "recxUn7lVietkIqvO", "recsvDIBM4fqDlQSI"]],
  ["Traumatic Disorders", ["recCeloI4rd5GD0H2", "recgPkjZWGRzqGa8Q", "recj9momAWjGvIP7d", "recMJHTwhHfNQrqyE", "recDldLmcZOo7GiGH", "recVFnUIMll27ml83", "recvuGgZL1pyzfrO5", "recGVz9TZSXlx5zKE", "recc48VMPETV7Kluf", "recGDRRX1xUyhklTT", "reccx35RQZUPHSBGb", "recfBmgc0xhsro3Mt", "reca7NqJQcfTsjQZk", "rec1sC11E1eKU6hll", "recId93zk6JIso3zM", "recBF61Q6tmz8NIuJ", "rec7AxuqZpiNgjvE2"]],
  ["Procedural and Skills", ["recMCz40D1LgRqs8T", "recHkDcr8jWfRjEwc", "recZ0SGEka96gghv1", "recZgCosgPtg3FWII", "recg6dyugvvq9K7V4", "recbEu0HgsYeoimwN"]],
  ["Other Core Competencies", ["recIwFwXcYX247uGu", "recDt4xL3Rm1SjfyX", "recpCy1coIoeIFD2V", "recOPPxEuCc9Jhdl6"]]
]);

export const subcatIdToName = new Map([
  ["recKAgx1cxL7kefAf", "Antiemetics"],
  ["recH6iAEcor3wE44X", "Overuse Syndromes"],
  ["recGlQKFDlSECQ9lY", "Personality Disorders"],
  ["rec9BQidrLQUR57nS", "Cardiovascular Tumors"],
  ["rec9ttUkW77bFKL6i", "Contraception"],
  ["rec5N0MuCgQPVmAxw", "Movement Disorders"],
  ["rec2hCbNWHfYLNMe1", "Local anesthetics"],
  ["recouDJgXjnqJQu3l", "Marine toxins"],
  ["recksSMDwSauBiO7R", " Factitious Disorders"],
  ["rechOMPSd5QXpV5su", "Renal and Urogenital Tumors"],
  ["rech28j02eeFYQjvA", "Thoracic and Respiratory Tumors"],
  ["receh67BOoIXNsboC", " Demyelinating Disorders"],
  ["recbsmsbSGSCs7pTd", "Cranial Nerve Disorders"],
  ["recwi3eXXTxQINhUw", "Soft Tissue Infections"],
  ["recaMVmSLBjZClZ8V", "Esophagus"],
  ["recJMGTuhry7QPgj3", "Acute Upper Airway Disorders"],
  ["recc1Uroa6gqV8Z0F", "Immune Complex Disorders"],
  ["recsvDIBM4fqDlQSI", "Acetaminophen Overdose"],
  ["recGtT8jLHAkyvbeH", "Household/Industrial chemicals"],
  ["recy2Ld0ruoPey4Wb", "Oncologic Emergencies"],
  ["receiNyLbrrv8uyXB", "Pulmonary Infections"],
  ["recC3M5tBSIJlYILV", "Heavy metals "],
  ["rec6hbI3e15WrxyB0", "Nutritional supplements"],
  ["recQTLbSPQq9CdJSv", "Lithium"],
  ["recriNs80mkkQVXZq", "Mushrooms/Poisonous plants"],
  ["recnjRJKZ6Zj4aMrR", "Sedatives/Hypnotics"],
  ["rec7ItIa2nizt2Lh1", "Stomach"],
  ["rechgN8lxnGfrB8YK", "Gall Bladder and Biliary Tract"],
  ["recU4OHHhTjtpQz5a", "Renal / Urogenital Infection"],
  ["recuETJrWf16YxRs5", " Male Genital Tract"],
  ["recfBmgc0xhsro3Mt", "Pediatric fractures"],
  ["recWAjlcGjeli6AqU", "High-Risk Pregnancy"],
  ["recZz2LzqHYvtXXPB", "Normal Labor and Delivery"],
  ["rec5H9ZYkercbhCN1", "Complications of Labor"],
  ["recdJqmAo6534cydc", "Substance Use Disorders"],
  ["recr1Fup2jyqdbupB", "General"],
  ["rect0JVhkFjJ3bnwy", "Pain"],
  ["recHkDcr8jWfRjEwc", "Resuscitation"],
  ["recWBANLvhSGQr0sg", "Mood Disorders and Thought Disorders"],
  ["recxH0upWZ4bZWOFq", "Acid-base Disturbances"],
  ["recQnoDBn5Yr3T6fz", " Herbicides, insecticides, and rodenticides"],
  ["recC5Ay9SMLbsgojV", "Cholinergics"],
  ["recGtsiGMkEcITWAT", "Biological Warfare Agents"],
  ["rec3z9Oas1acbRoTa", "Medication-induced Immunosuppression"],
  ["recId93zk6JIso3zM", "Spinal cord and nervous system trauma"],
  ["recyDlkkqtC1iSfpm", "Hypersensitivity"],
  ["rec58vK6jK35cC7KL", "Bony Abnormalities"],
  ["recGVz9TZSXlx5zKE", "Extremity bony trauma"],
  ["recceX6Jl9NiiklDr", "Bites and Envenomation"],
  ["recDldLmcZOo7GiGH", "Genitourinary trauma"],
  ["recCeloI4rd5GD0H2", "Abdominal trauma"],
  ["recjUKyeGosQgfG6o", "Endocarditis"],
  ["reccx35RQZUPHSBGb", "Otologic trauma"],
  ["recX9XqMLzyNTixND", "Diseases of the Myocardium, Acquired"],
  ["recFVZq1ceunskqOc", "Methemoglobinemia"],
  ["rec1sC11E1eKU6hll", "Soft-tissue extremity injuries"],
  ["rec3Z9F2pGhkN85gD", "Acute Respiratory Distress Syndrome"],
  ["rec341CAEeWi3DiIp", "Peritoneum"],
  ["recj9momAWjGvIP7d", "Cutaneous injuries"],
  ["rec4pa7OP40DcjpMS", "Pancytopenia"],
  ["reccRLnAThF2csQEF", "Structural Disorders"],
  ["recDQNtd083Q7T20f", "Kawasaki Disease"],
  ["recxWIwYBSNOPI9d1", "Disorders of Circulation"],
  ["recLo64cZ2bqaioF4", "Collagen Vascular Disease"],
  ["recR2UZK5fcq5Eib3", "Seizure Disorders"],
  ["rec6BhlaiZtcprdLq", "Disturbances of Cardiac Rhythm"],
  ["recaBCvjTBCy0plfl", "Hypertension"],
  ["recl9aog6ghHPdFhb", "Viral Infections"],
  ["recgPkjZWGRzqGa8Q", "Chest trauma"],
  ["recDt4xL3Rm1SjfyX", "Practice-based Learning and Improvement"],
  ["recd44WiR7l0wukbW", "Cardiovascular Devices"],
  ["rectRDjFmQyaq7VBY", "White Blood Cell Disorders"],
  ["recg973IkpUQyBgdk", "Liver"],
  ["recVFnUIMll27ml83", "Head trauma"],
  ["recN9R3Wg2xYxiBmc", "Emerging Infections/Pandemics"],
  ["recnu0rZfX3kHr7Ci", "Tick-Borne Infections"],
  ["recPlaKdsJXoxVhES", "Congenital Abnormalities of the Cardiovascular System"],
  ["reccsRdpMFPJuJyAY", "Large Bowel"],
  ["recAFXExPijhWGe0Y", "Complications of Renal Dialysis"],
  ["rec0FNwCpw2XXUhhh", "Ulcerative Lesions"],
  ["recmj3rxPYxrIbqdp", "Maculopapular Lesions"],
  ["recq8zFcZqPGsdUnt", "Pulmonary Hypertension"],
  ["recn3JB7mF5jxMwZ5", "Neuromuscular Disorders"],
  ["recSzpAw2UPxgpaUL", "Glomerular Disorders"],
  ["recMCz40D1LgRqs8T", "Airway Techniques"],
  ["rec69uGKTlheOYBJj", " Disorders of Pleura, Mediastinum, and Chest Wall"],
  ["recfZruB0Q0aKUP14", "Rectum and Anus"],
  ["recBF61Q6tmz8NIuJ", "Trauma in Pregnancy"],
  ["recs9rSzz3o8EBFO4", "Spleen"],
  ["rec76RTdWeybZXMZ6", "Transplant-related Problems"],
  ["recPiEHNaZstKOV0r", "Valvular Disorders"],
  ["recC4oXaYFlsc9s4Q", "Parathyroid Disease"],
  ["recN6SjYY8oXR8hks", "Lymphomas"],
  ["recc48VMPETV7Kluf", "Neck trauma"],
  ["recvDudvWQ7w6opAL", "Nose"],
  ["recvJ6oNl7jYmdcPp", "Temperature-related Illness"],
  ["rechPXDlzx67qpCoD", "Female Genital Tract"],
  ["reci7SAedjmVsR6NZ", "Protozoan/Parasites"],
  ["reciOYqx0IvFrJQTu", "Eye"],
  ["rec14BkxDX3unLfnk", "Other Conditions of the Brain"],
  ["rec2pxcKFWVZ8TJ9i", " Headache"],
  ["recGDRRX1xUyhklTT", "Ophthalmologic trauma"],
  ["recZgCosgPtg3FWII", "Diagnostic and Therapeutic Procedures"],
  ["recAU9gIycCuykaQ7", "Joint Abnormalities"],
  ["recOPPxEuCc9Jhdl6", "Systems-based Practice"],
  ["recs0wa5zFNGI0ydD", "Disease of myocardium (acquired)"],
  ["rec3bYe45fmlphxvr", "Pulmonary Embolism/Infarct"],
  ["recgumnA7uX0qSBub", "Blood Transfusion"],
  ["recOfMFQYud4EVuB0", "Red Blood Cell Disorders"],
  ["recWllgwwNeQawtws", "Infections/Inflammatory Disorders of the Nervous System"],
  ["recL8oXUExUc3VN5L", "STEMI"],
  ["recglOC1p7xyNNH3y", "Cardiopulmonary Arrest"],
  ["rec3CVZb9tf10EZiJ", "Diseases of the Pericardium"],
  ["recK065jpAdzeqtXN", "Abnormal Vital Signs"],
  ["rec1aKvigo17k14Eq", "Post-surgical Complications of the Abdomen"],
  ["recKsHp4wINiGn1U9", "Fungal Infections"],
  ["recLoFNVXYSG5C8oP", "Antimicrobials"],
  ["reclw2QQSTOEZPQ9L", "Antidepressants"],
  ["recTlSlT9LPMfqcHd", "Cardiovascular drugs"],
  ["recxUn7lVietkIqvO", "Stimulants/Sympathomimetics"],
  ["recCU8B4Ax2awTCRh", "Recreational drugs"],
  ["reccMnB7rx69FK0Tj", "Carbon monoxide"],
  ["reclvRnhUnm8pjn2L", "Cyanides, hydrogen sulfide "],
  ["recSq2XIAnT6NxIqN", "Fluid and Electrolyte Disturbances"],
  ["recrYtWkA2Thmzefb", "Postpartum Complications"],
  ["recvuGgZL1pyzfrO5", "Injuries of the spine"],
  ["reca7NqJQcfTsjQZk", "Pelvic fracture "],
  ["recNXPMmeAFpNhz7b", "Analgesics"],
  ["rechx9fuCcyuwhKqt", "Nutritional Disorders"],
  ["rec237hgtSJGOMNgf", "Glucose Metabolism"],
  ["recKjze3JpZAZITvv", "Oropharynx/Throat"],
  ["recTudqZywHkUEHlh", "Stroke"],
  ["recrf8wLK77Izk0kP", "Ear"],
  ["recFzXJWzYIiOfdsV", "Hydrocephalus"],
  ["recIBCq90KVqT4sb2", "Hypoglycemics/Insulin"],
  ["recGE77ZAWvCuM7zw", "Anticholinergics"],
  ["recIZMJMt7WgltTal", "Cutaneous Infections"],
  ["recPCN4LoFYOaSlHu", "Adrenal Disease"],
  ["reco2hohS8aaylq2s", "Pancreas"],
  ["recc5CCodkkJF41iT", "Complications of Delivery"],
  ["rec8204KedeGtEjLg", "Drug Resistance"],
  ["rec3sjGSFAjoGg6B4", "Thyroid Disorders"],
  ["recwd5mGO6tLoEo8V", "Small Bowel"],
  ["recdP5ezk8JhRcWgh", "Bacterial Infections"],
  ["recRex7KAFAyBQF9c", "Obstructive/Restrictive Lung Disease"],
  ["rec3y0Cs09CnuwwZW", "Hemostatic Disorders"],
  ["recZ2YjN9ZVHohlSQ", "Cancers of the Skin"],
  ["recyD6USONqJrWpA9", "Endocrine Tumors"],
  ["recOUSndwlaEq9riN", "Anticoagulants/Antithrombotics"],
  ["rec7AxuqZpiNgjvE2", "Multi-system Trauma"],
  ["recg6dyugvvq9K7V4", "Ultrasound"],
  ["recbEu0HgsYeoimwN", "Other Diagnostic and Therapeutic Procedures"],
  ["recvZqXSYh788HjcI", "Urolithiasis"],
  ["rec03V8FcuxkttRYj", "Patterns of Violence/Abuse/Neglect"],
  ["recpNb536JE5wmrqQ", "Electrical Injury"],
  ["recZ0SGEka96gghv1", "Anesthesia and Acute Pain Management"],
  ["reczaBYFWSfdlhy96", "Alcohol"],
  ["reczSKXrXg8jeFUdj", "Psychosomatic Disorders"],
  ["recPQu8AZy6FhzuEX", "Antipsychotics "],
  ["rec4DBjI1AEoQjv2d", "Organic Psychoses"],
  ["recpCy1coIoeIFD2V", "Professionalism"],
  ["reczFaMav53fnupv3", "HEENT Tumors"],
  ["recRiEjq8LHfwNveO", "Complications of Pregnancy"],
  ["recHVFjCyEAMrV93r", "High-altitude Illness"],
  ["recaJGPEFVcHJpb4F", "Transient Cerebral Ischemia "],
  ["recyszhwrHPU6uFFq", "Spinal Cord Compression "],
  ["recL1VhuB5fFhtNhZ", "Delirium"],
  ["recmFZ0LAH71eevpo", "Normal Pregnancy"],
  ["recMyaspBGgXoIqmG", "Anticonvulsants "],
  ["recMJHTwhHfNQrqyE", "Facial fractures"],
  ["recjZ7Ph0ONQmNMSm", "Acute and Chronic Renal Failure"],
  ["recmiZVxrrSCBQqi5", "Nephritis"],
  ["recJdsL9BMhWlnmFj", "Abdominal Wall"],
  ["recLpL3uRIqRdcwjO", "Disorders of the Spine"],
  ["recwB6bpmHU75cfdP", "Nervous System Tumors"],
  ["recaJKw0GmnRlrdI4", "Dysbarism"],
  ["recqlDwpw9a9bXYVK", "Neurotic Disorders"],
  ["rec9bJXGp7CszROax", "Dermatitis"],
  ["recXsQKuVMFUQ3VEi", "Papular/Nodular Lesions"],
  ["recn4szGxwB8oiJWh", "Vesicular/Bullous Lesions"],
  ["recEbDuBNNPPq6t4f", "Physical and Chemical Irritants/Insults"],
  ["recIwFwXcYX247uGu", "Interpersonal and Communication Skills "],
  ["recafha6TQdKgXLeL", "Submersion Incidents"],
  ["recoG2XwYHTETJoXy", "Radiation Emergencies"],
  ["recXSVPcE2UTdQ754", "Muscle Abnormalities"],
  ["recPPc0zjj3bCLdUB", "Pituitary Disorders"],
  ["rechTZxjYUsHwQ0vS", "undefined"],
])